package com.restaurant.order_service.dto;

import jakarta.validation.constraints.NotBlank;

public record FinalSubmitKOTRequest(

        @NotBlank(message = "Generated by is required")
        String generatedBy
) {
}