package com.restaurant.order_service.service;

import com.restaurant.order_service.dto.KOTResponse;
import com.restaurant.order_service.entity.KOT;
import com.restaurant.order_service.entity.KOTStatus;
import com.restaurant.order_service.entity.Order;
import com.restaurant.order_service.entity.OrderStatus;
import com.restaurant.order_service.repository.KOTRepository;
import com.restaurant.order_service.repository.OrderRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class KOTService {

    private final KOTRepository kotRepository;
    private final OrderRepository orderRepository;


    // =====================================================
    // GENERATE KOT
    // =====================================================

    @Transactional
    public KOTResponse generateKOT(
            Long orderId,
            String generatedBy
    ) {

        log.info(
                "Generating KOT | orderId={} | generatedBy={}",
                orderId,
                generatedBy
        );


        // -------------------------------------------------
        // FIND ORDER
        // -------------------------------------------------

        Order order =
                orderRepository.findById(orderId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Order not found with id: "
                                                + orderId
                                )
                        );


        // -------------------------------------------------
        // ORDER STATUS VALIDATION
        // -------------------------------------------------

        if (order.getStatus() != OrderStatus.ACCEPTED) {

            throw new RuntimeException(
                    "KOT can be generated only for an ACCEPTED order. "
                            + "Current status: "
                            + order.getStatus()
            );
        }


        // -------------------------------------------------
        // CHECK EXISTING KOT
        // -------------------------------------------------

        if (kotRepository.existsByOrderId(orderId)) {

            log.warn(
                    "KOT already exists | orderId={}",
                    orderId
            );

            throw new RuntimeException(
                    "KOT already exists for order: "
                            + orderId
            );
        }


        // -------------------------------------------------
        // VALIDATE GENERATED BY
        // -------------------------------------------------

        if (
                generatedBy == null
                        || generatedBy.isBlank()
        ) {

            generatedBy = "RESTAURANT_STAFF";
        }


        // -------------------------------------------------
        // CREATE KOT
        // -------------------------------------------------

        KOT kot =
                KOT.builder()
                        .orderId(order.getId())
                        .tableId(order.getTableId())
                        .status(KOTStatus.GENERATED)
                        .generatedBy(generatedBy)
                        .build();


        kot =
                kotRepository.save(kot);


        log.info(
                "KOT generated successfully | kotId={} | orderId={} | status={}",
                kot.getId(),
                kot.getOrderId(),
                kot.getStatus()
        );


        return buildResponse(kot);
    }


    // =====================================================
    // START PREPARING
    // =====================================================

    @Transactional
    public KOTResponse startPreparing(
            Long kotId
    ) {

        log.info(
                "Starting KOT preparation | kotId={}",
                kotId
        );


        KOT kot =
                getKOT(kotId);


        if (kot.getStatus() != KOTStatus.GENERATED) {

            throw new RuntimeException(
                    "KOT cannot move to PREPARING from status: "
                            + kot.getStatus()
            );
        }


        kot.setStatus(
                KOTStatus.PREPARING
        );


        kot =
                kotRepository.save(kot);


        log.info(
                "KOT moved to PREPARING | kotId={}",
                kotId
        );


        // -------------------------------------------------
        // UPDATE ORDER STATUS
        // -------------------------------------------------

        Order order =
                getOrder(kot.getOrderId());


        if (order.getStatus() != OrderStatus.ACCEPTED) {

            throw new RuntimeException(
                    "Order cannot move to PREPARING from status: "
                            + order.getStatus()
            );
        }


        order.setStatus(
                OrderStatus.PREPARING
        );


        orderRepository.save(order);


        log.info(
                "Order moved to PREPARING | orderId={}",
                order.getId()
        );


        return buildResponse(kot);
    }


    // =====================================================
    // MARK KOT READY
    // =====================================================

    @Transactional
    public KOTResponse markReady(
            Long kotId
    ) {

        log.info(
                "Marking KOT READY | kotId={}",
                kotId
        );


        KOT kot =
                getKOT(kotId);


        if (kot.getStatus() != KOTStatus.PREPARING) {

            throw new RuntimeException(
                    "KOT cannot move to READY from status: "
                            + kot.getStatus()
            );
        }


        kot.setStatus(
                KOTStatus.READY
        );


        kot =
                kotRepository.save(kot);


        // -------------------------------------------------
        // UPDATE ORDER
        // -------------------------------------------------

        Order order =
                getOrder(kot.getOrderId());


        if (order.getStatus() != OrderStatus.PREPARING) {

            throw new RuntimeException(
                    "Order cannot move to READY from status: "
                            + order.getStatus()
            );
        }


        order.setStatus(
                OrderStatus.READY
        );


        orderRepository.save(order);


        log.info(
                "Order moved to READY | orderId={} | kotId={}",
                order.getId(),
                kotId
        );


        return buildResponse(kot);
    }


    // =====================================================
    // GET KOT BY ID
    // =====================================================

    public KOTResponse getKOTById(
            Long kotId
    ) {

        return buildResponse(
                getKOT(kotId)
        );
    }


    // =====================================================
    // GET KOT BY ORDER
    // =====================================================

    public KOTResponse getKOTByOrderId(
            Long orderId
    ) {

        KOT kot =
                kotRepository
                        .findByOrderId(orderId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "KOT not found for order: "
                                                + orderId
                                )
                        );


        return buildResponse(kot);
    }


    // =====================================================
    // GET KOTS BY STATUS
    // =====================================================

    public List<KOTResponse> getKOTsByStatus(
            KOTStatus status
    ) {

        return kotRepository
                .findByStatusOrderByCreatedAtAsc(status)
                .stream()
                .map(this::buildResponse)
                .toList();
    }


    // =====================================================
    // GET ALL KOTS
    // =====================================================

    public List<KOTResponse> getAllKOTs() {

        return kotRepository
                .findAllByOrderByCreatedAtDesc()
                .stream()
                .map(this::buildResponse)
                .toList();
    }


    // =====================================================
    // FIND KOT
    // =====================================================

    private KOT getKOT(
            Long kotId
    ) {

        return kotRepository
                .findById(kotId)
                .orElseThrow(() ->
                        new RuntimeException(
                                "KOT not found with id: "
                                        + kotId
                        )
                );
    }


    // =====================================================
    // FIND ORDER
    // =====================================================

    private Order getOrder(
            Long orderId
    ) {

        return orderRepository
                .findById(orderId)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Order not found with id: "
                                        + orderId
                        )
                );
    }


    // =====================================================
    // BUILD RESPONSE
    // =====================================================

    private KOTResponse buildResponse(
            KOT kot
    ) {

        return new KOTResponse(
                kot.getId(),
                kot.getOrderId(),
                kot.getTableId(),
                kot.getStatus(),
                kot.getGeneratedBy(),
                kot.getCreatedAt(),
                kot.getUpdatedAt()
        );
    }
}